---
# tasks file for java

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Update yum cache
  yum:
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install Java
  apt:
    name: "{{ java_version }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Java
  yum:
    name: "{{ java_version }}"
  when: ansible_os_family == 'RedHat'
